export const trandingCollection = [
  {
    name: "Graphic Print T-Shirt",
    image: "/images/trending/tshirts.webp",
    price: "399",
    ratings: 4,
    type: "T-Shirt",
  },
  {
    name: "Plain Cotton T-Shirt",
    image: "/images/trending/thsirts.webp",
    price: "349",
    ratings: 5,
    type: "T-Shirt",
  },
  {
    name: "Slim Fit Shirt",
    image: "/images/trending/shirts.jpg",
    price: "499",
    ratings: 4,
    type: "Shirt",
  },
  {
    name: "Tapered Cargo Pants",
    image: "/images/trending/cargo2.webp",
    price: "739",
    ratings: 3,
    type: "Cargo",
  },
  {
    name: "Sports Shorts",
    image: "/images/trending/shorts.webp",
    price: "299",
    ratings: 5,
    type: "Shorts",
  },
  {
    name: "Casual Cotton Shorts",
    image: "/images/trending/shortss.webp",
    price: "349",
    ratings: 4,
    type: "Shorts",
  },
  {
    name: "Formal Trousers",
    image: "/images/trending/jeans.webp",
    price: "659",
    ratings: 5,
    type: "Trousers",
  },
  {
    name: "Relaxed Fit Trousers",
    image: "/images/trending/cargo.jpg",
    price: "599",
    ratings: 3,
    type: "Trousers",
  },
  {
    name: "Graphic Print T-Shirt",
    image: "/images/trending/tshirts.webp",
    price: "399",
    ratings: 4,
    type: "T-Shirt",
  },
  {
    name: "Plain Cotton T-Shirt",
    image: "/images/trending/thsirts.webp",
    price: "349",
    ratings: 5,
    type: "T-Shirt",
  },
  {
    name: "Slim Fit Shirt",
    image: "/images/trending/shirts.jpg",
    price: "499",
    ratings: 4,
    type: "Shirt",
  },
  {
    name: "Checked Casual Shirt",
    image: "/images/trending/shirts1.webp",
    price: "549",
    ratings: 3,
    type: "Shirt",
  },
  {
    name: "Classic Denim Jeans",
    image: "/images/trending/jeans.avif",
    price: "799",
    ratings: 5,
    type: "Jeans",
  },
  {
    name: "Stretch Skinny Jeans",
    image: "/images/trending/jeans.webp",
    price: "849",
    ratings: 4,
    type: "Jeans",
  },
  {
    name: "Relaxed Fit Cargo Pants",
    image: "/images/trending/cargo.jpg",
    price: "699",
    ratings: 4,
    type: "Cargo",
  },

  {
    name: "Classic Denim Jeans",
    image: "/images/trending/jeans.avif",
    price: "799",
    ratings: 5,
    type: "Jeans",
  },
  {
    name: "Stretch Skinny Jeans",
    image: "/images/trending/jeans.webp",
    price: "849",
    ratings: 4,
    type: "Jeans",
  },
  {
    name: "Relaxed Fit Cargo Pants",
    image: "/images/trending/cargo.jpg",
    price: "699",
    ratings: 4,
    type: "Cargo",
  },
  {
    name: "Tapered Cargo Pants",
    image: "/images/trending/cargo2.webp",
    price: "739",
    ratings: 3,
    type: "Cargo",
  },
  {
    name: "Sports Shorts",
    image: "/images/trending/shorts.webp",
    price: "299",
    ratings: 5,
    type: "Shorts",
  },
  {
    name: "Casual Cotton Shorts",
    image: "/images/trending/shortss.webp",
    price: "349",
    ratings: 4,
    type: "Shorts",
  },
  {
    name: "Formal Trousers",
    image: "/images/trending/jeans.webp",
    price: "659",
    ratings: 5,
    type: "Trousers",
  },
  {
    name: "Relaxed Fit Trousers",
    image: "/images/trending/cargo.jpg",
    price: "599",
    ratings: 3,
    type: "Trousers",
  },
  {
    name: "Graphic Print T-Shirt",
    image: "/images/trending/tshirts.webp",
    price: "399",
    ratings: 4,
    type: "T-Shirt",
  },
  {
    name: "Plain Cotton T-Shirt",
    image: "/images/trending/thsirts.webp",
    price: "349",
    ratings: 5,
    type: "T-Shirt",
  },
  {
    name: "Slim Fit Shirt",
    image: "/images/trending/shirts.jpg",
    price: "499",
    ratings: 4,
    type: "Shirt",
  },
  {
    name: "Checked Casual Shirt",
    image: "/images/trending/shirts1.webp",
    price: "549",
    ratings: 3,
    type: "Shirt",
  },
  {
    name: "Classic Denim Jeans",
    image: "/images/trending/jeans.avif",
    price: "799",
    ratings: 5,
    type: "Jeans",
  },
  {
    name: "Stretch Skinny Jeans",
    image: "/images/trending/jeans.webp",
    price: "849",
    ratings: 4,
    type: "Jeans",
  },
  {
    name: "Relaxed Fit Cargo Pants",
    image: "/images/trending/cargo.jpg",
    price: "699",
    ratings: 4,
    type: "Cargo",
  },
  {
    name: "Tapered Cargo Pants",
    image: "/images/trending/cargo2.webp",
    price: "739",
    ratings: 3,
    type: "Cargo",
  },
  {
    name: "Sports Shorts",
    image: "/images/trending/shorts.webp",
    price: "299",
    ratings: 5,
    type: "Shorts",
  },
  {
    name: "Casual Cotton Shorts",
    image: "/images/trending/shortss.webp",
    price: "349",
    ratings: 4,
    type: "Shorts",
  },
  {
    name: "Formal Trousers",
    image: "/images/trending/jeans.webp",
    price: "659",
    ratings: 5,
    type: "Trousers",
  },
  {
    name: "Relaxed Fit Trousers",
    image: "/images/trending/cargo.jpg",
    price: "599",
    ratings: 3,
    type: "Trousers",
  },
  {
    name: "Graphic Print T-Shirt",
    image: "/images/trending/tshirts.webp",
    price: "399",
    ratings: 4,
    type: "T-Shirt",
  },
  {
    name: "Plain Cotton T-Shirt",
    image: "/images/trending/thsirts.webp",
    price: "349",
    ratings: 5,
    type: "T-Shirt",
  },
  {
    name: "Slim Fit Shirt",
    image: "/images/trending/shirts.jpg",
    price: "499",
    ratings: 4,
    type: "Shirt",
  },
  {
    name: "Checked Casual Shirt",
    image: "/images/trending/shirts1.webp",
    price: "549",
    ratings: 3,
    type: "Shirt",
  },
  {
    name: "Classic Denim Jeans",
    image: "/images/trending/jeans.avif",
    price: "799",
    ratings: 5,
    type: "Jeans",
  },

  {
    name: "Relaxed Fit Trousers",
    image: "/images/trending/cargo.jpg",
    price: "599",
    ratings: 3,
    type: "Trousers",
  },
];
