export const winterCollectionApi = [
  {
    name: "Graphic Print Sweatshirt",
    image: "/images/trending/tshirts.webp",
    price: "399",
    ratings: 4,
    type: "Sweatshirt",
  },
  {
    name: "Plain Cotton Sweatshirt",
    image: "/images/trending/thsirts.webp",
    price: "349",
    ratings: 5,
    type: "Sweatshirt",
  },
  {
    name: "Slim FiSweatshirt",
    image: "/images/trending/shirts.jpg",
    price: "499",
    ratings: 4,
    type: "Sweatshirt",
  },
  {
    name: "Tapered Jacket Pants",
    image: "/images/trending/cargo2.webp",
    price: "739",
    ratings: 3,
    type: "Jacket",
  },
  {
    name: "Sports Hoodie",
    image: "/images/trending/shorts.webp",
    price: "299",
    ratings: 5,
    type: "Hoodie",
  },
  {
    name: "Casual Cotton Hoodie",
    image: "/images/trending/shortss.webp",
    price: "349",
    ratings: 4,
    type: "Hoodie",
  },
  {
    name: "Formal Sweater",
    image: "/images/trending/jeans.webp",
    price: "659",
    ratings: 5,
    type: "Sweater",
  },
  {
    name: "Relaxed Fit Sweater",
    image: "/images/trending/cargo.jpg",
    price: "599",
    ratings: 3,
    type: "Sweater",
  },
  {
    name: "Graphic Print Sweatshirt",
    image: "/images/trending/tshirts.webp",
    price: "399",
    ratings: 4,
    type: "Sweatshirt",
  },
  {
    name: "Plain Cotton Sweatshirt",
    image: "/images/trending/thsirts.webp",
    price: "349",
    ratings: 5,
    type: "Sweatshirt",
  },
  {
    name: "Slim FiSweatshirt",
    image: "/images/trending/shirts.jpg",
    price: "499",
    ratings: 4,
    type: "Sweatshirt",
  },
  {
    name: "Checked CasuaSweatshirt",
    image: "/images/trending/shirts1.webp",
    price: "549",
    ratings: 3,
    type: "Sweatshirt",
  },
  {
    name: "Classic Denim Jeans",
    image: "/images/trending/jeans.avif",
    price: "799",
    ratings: 5,
    type: "Jeans",
  },
  {
    name: "Stretch Skinny Jeans",
    image: "/images/trending/jeans.webp",
    price: "849",
    ratings: 4,
    type: "Jeans",
  },
  {
    name: "Relaxed Fit Jacket Pants",
    image: "/images/trending/cargo.jpg",
    price: "699",
    ratings: 4,
    type: "Jacket",
  },

  {
    name: "Classic Denim Jeans",
    image: "/images/trending/jeans.avif",
    price: "799",
    ratings: 5,
    type: "Jeans",
  },
  {
    name: "Stretch Skinny Jeans",
    image: "/images/trending/jeans.webp",
    price: "849",
    ratings: 4,
    type: "Jeans",
  },
  {
    name: "Relaxed Fit Jacket Pants",
    image: "/images/trending/cargo.jpg",
    price: "699",
    ratings: 4,
    type: "Jacket",
  },
  {
    name: "Tapered Jacket Pants",
    image: "/images/trending/cargo2.webp",
    price: "739",
    ratings: 3,
    type: "Jacket",
  },
  {
    name: "Sports Hoodie",
    image: "/images/trending/shorts.webp",
    price: "299",
    ratings: 5,
    type: "Hoodie",
  },
  {
    name: "Casual Cotton Hoodie",
    image: "/images/trending/shortss.webp",
    price: "349",
    ratings: 4,
    type: "Hoodie",
  },
  {
    name: "Formal Sweater",
    image: "/images/trending/jeans.webp",
    price: "659",
    ratings: 5,
    type: "Sweater",
  },
  {
    name: "Relaxed Fit Sweater",
    image: "/images/trending/cargo.jpg",
    price: "599",
    ratings: 3,
    type: "Sweater",
  },
  {
    name: "Graphic Print Sweatshirt",
    image: "/images/trending/tshirts.webp",
    price: "399",
    ratings: 4,
    type: "Sweatshirt",
  },
  {
    name: "Plain Cotton Sweatshirt",
    image: "/images/trending/thsirts.webp",
    price: "349",
    ratings: 5,
    type: "Sweatshirt",
  },
  {
    name: "Slim FiSweatshirt",
    image: "/images/trending/shirts.jpg",
    price: "499",
    ratings: 4,
    type: "Sweatshirt",
  },
  {
    name: "Checked CasuaSweatshirt",
    image: "/images/trending/shirts1.webp",
    price: "549",
    ratings: 3,
    type: "Sweatshirt",
  },
  {
    name: "Classic Denim Jeans",
    image: "/images/trending/jeans.avif",
    price: "799",
    ratings: 5,
    type: "Jeans",
  },
  {
    name: "Stretch Skinny Jeans",
    image: "/images/trending/jeans.webp",
    price: "849",
    ratings: 4,
    type: "Jeans",
  },
  {
    name: "Relaxed Fit Jacket Pants",
    image: "/images/trending/cargo.jpg",
    price: "699",
    ratings: 4,
    type: "Jacket",
  },
  {
    name: "Tapered Jacket Pants",
    image: "/images/trending/cargo2.webp",
    price: "739",
    ratings: 3,
    type: "Jacket",
  },
  {
    name: "Sports Hoodie",
    image: "/images/trending/shorts.webp",
    price: "299",
    ratings: 5,
    type: "Hoodie",
  },
  {
    name: "Casual Cotton Hoodie",
    image: "/images/trending/shortss.webp",
    price: "349",
    ratings: 4,
    type: "Hoodie",
  },
  {
    name: "Formal Sweater",
    image: "/images/trending/jeans.webp",
    price: "659",
    ratings: 5,
    type: "Sweater",
  },
  {
    name: "Relaxed Fit Sweater",
    image: "/images/trending/cargo.jpg",
    price: "599",
    ratings: 3,
    type: "Sweater",
  },
  {
    name: "Graphic Print Sweatshirt",
    image: "/images/trending/tshirts.webp",
    price: "399",
    ratings: 4,
    type: "Sweatshirt",
  },
  {
    name: "Plain Cotton Sweatshirt",
    image: "/images/trending/thsirts.webp",
    price: "349",
    ratings: 5,
    type: "Sweatshirt",
  },
  {
    name: "Slim FiSweatshirt",
    image: "/images/trending/shirts.jpg",
    price: "499",
    ratings: 4,
    type: "Sweatshirt",
  },
  {
    name: "Checked CasuaSweatshirt",
    image: "/images/trending/shirts1.webp",
    price: "549",
    ratings: 3,
    type: "Sweatshirt",
  },
  {
    name: "Classic Denim Jeans",
    image: "/images/trending/jeans.avif",
    price: "799",
    ratings: 5,
    type: "Jeans",
  },

  {
    name: "Relaxed Fit Sweater",
    image: "/images/trending/cargo.jpg",
    price: "599",
    ratings: 3,
    type: "Sweater",
  },
];
