import type {
  IBottomEnums,
  IFilters,
  ITopEnums,
  tColors,
  tSizes,
  tFits,
} from "$/types/api";

export const color: tColors[] = [
  "beige",
  "blue",
  "gold",
  "silver",
  "green",
  "gray",
  "multicolor",
  "orange",
  "red",
  "black",
  "pink",
  "purple",
  "white",
  "yellow",
  "brown",
];

export const fit: tFits[] = [
  "slimFit",
  "oversized",
  "regularFit",
  "relaxedFit",
];

export const sortBy: IFilters["sortBy"] = [
  "popular",
  "newest",
  "oldest",
  "top-rated",
];

export const size: tSizes[] = ["s", "m", "l", "xl", "xxl", "xxxl"];

export const topEnums: ITopEnums = {
  fabric: [
    "cotton",
    "linen",
    "polyester",
    "wool",
    "silk",
    "denim",
    "fleece",
    "hemp",
    "velvet",
    "nylon",
  ],

  design: [
    "solidColor",
    "stripped",
    "checked",
    "printed",
    "graphic",
    "embroidered",
    "floralPatterned",
  ],

  style: [
    "tShirt",
    "basicTShirt",
    "poloTShirt",
    "henleyTShirt",
    "vNeckTShirt",
    "shirt",
    "casualShirt",
    "formalShirt",
    "linenShirt",
    "denimShirt",
    "buttonDownShirt",
    "sweatShirt",
    "hoodie",
    "jacket",
    "denimJacket",
    "leatherJacket",
    "longSleeveTop",
    "sweater",
  ],

  sleeveType: [
    "shortSleeve",
    "longSleeve",
    "sleeveless",
    "halfSleeve",
    "fiveSleeve",
  ],

  occasion: ["casual", "sportswear", "loungewear", "vacation"],
  fit,
  season: ["summer", "winter", "allSeason", "rainy"],
  size,
  color,
};

export const bottomEnums: IBottomEnums = {
  fabric: [
    "cotton",
    "linen",
    "polyester",
    "denim",
    "fleece",
    "nylon",
    "spandex",
    "canvas",
    "wool",
  ],
  style: ["trackPants", "cargoPants", "joggers", "shorts", "trousers"],
  fit,
  size,
  color,
};

export const topLinks = [
  {
    title: "Tops",
    href: "/tops",
    desc: "All Tops",
  },
  {
    title: "Shirts",
    href: "/tops?style=shirt",
    desc: "Casual wear",
  },
  {
    title: "Casual Shirts",
    href: "/tops?style=casualShirt",
    desc: "Easygoing shirts",
  },
  {
    title: "Formal Shirts",
    href: "/tops?style=formalShirt",
    desc: "Business attire",
  },
  {
    title: "T-Shirts",
    href: "/tops?style=tShirt",
    desc: "Basic essentials",
  },
  {
    title: "Polo T-Shirts",
    href: "/tops?style=poloTShirt",
    desc: "Preppy style",
  },
  {
    title: "Hoodies",
    href: "/tops?style=hoodie",
    desc: "Cozy comfort",
  },
  {
    title: "Long Sleeve Tops",
    href: "/tops?style=longSleeveTop",
    desc: "All-weather wear",
  },
  {
    title: "Sweatshirts",
    href: "/tops?style=sweatShirt",
    desc: "Sporty vibes",
  },
  {
    title: "Jackets",
    href: "/tops?style=jacket",
    desc: "Outerwear",
  },
  {
    title: "Denim Jackets",
    href: "/tops?style=denimJacket",
    desc: "Classic denim",
  },
];

export const bottomLinks = [
  {
    title: "Bottoms",
    href: "/bottoms",
    desc: "All Bottoms",
  },
  {
    title: "Track Pants",
    href: "/bottoms?style=trackPants",
    desc: "Sporty comfort",
  },
  {
    title: "Cargo Pants",
    href: "/bottoms?style=cargoPants",
    desc: "Utility style",
  },
  {
    title: "Joggers",
    href: "/bottoms?style=joggers",
    desc: "Casual fit",
  },
  {
    title: "Shorts",
    href: "/bottoms?style=shorts",
    desc: "Warm weather",
  },
  {
    title: "Trousers",
    href: "/bottoms?style=trousers",
    desc: "Formal wear",
  },
];
export const countryDialingCodes = [
  { countryCode: "AC", dialingCode: 247 },
  { countryCode: "AD", dialingCode: 376 },
  { countryCode: "AE", dialingCode: 971 },
  { countryCode: "AF", dialingCode: 93 },
  { countryCode: "AG", dialingCode: 1268 },
  { countryCode: "AI", dialingCode: 1264 },
  { countryCode: "AL", dialingCode: 355 },
  { countryCode: "AM", dialingCode: 374 },
  { countryCode: "AO", dialingCode: 244 },
  { countryCode: "AR", dialingCode: 54 },
  { countryCode: "AS", dialingCode: 1684 },
  { countryCode: "AT", dialingCode: 43 },
  { countryCode: "AU", dialingCode: 61 },
  { countryCode: "AW", dialingCode: 297 },
  { countryCode: "AX", dialingCode: 358 },
  { countryCode: "AZ", dialingCode: 994 },
  { countryCode: "BA", dialingCode: 387 },
  { countryCode: "BB", dialingCode: 1246 },
  { countryCode: "BD", dialingCode: 880 },
  { countryCode: "BE", dialingCode: 32 },
  { countryCode: "BF", dialingCode: 226 },
  { countryCode: "BG", dialingCode: 359 },
  { countryCode: "BH", dialingCode: 973 },
  { countryCode: "BI", dialingCode: 257 },
  { countryCode: "BJ", dialingCode: 229 },
  { countryCode: "BL", dialingCode: 590 },
  { countryCode: "BM", dialingCode: 1441 },
  { countryCode: "BN", dialingCode: 673 },
  { countryCode: "BO", dialingCode: 591 },
  { countryCode: "BQ", dialingCode: 599 },
  { countryCode: "BR", dialingCode: 55 },
  { countryCode: "BS", dialingCode: 1242 },
  { countryCode: "BT", dialingCode: 975 },
  { countryCode: "BW", dialingCode: 267 },
  { countryCode: "BY", dialingCode: 375 },
  { countryCode: "BZ", dialingCode: 501 },
  { countryCode: "CA", dialingCode: 1 },
  { countryCode: "CC", dialingCode: 61 },
  { countryCode: "CD", dialingCode: 243 },
  { countryCode: "CF", dialingCode: 236 },
  { countryCode: "CG", dialingCode: 242 },
  { countryCode: "CH", dialingCode: 41 },
  { countryCode: "CI", dialingCode: 225 },
  { countryCode: "CK", dialingCode: 682 },
  { countryCode: "CL", dialingCode: 56 },
  { countryCode: "CM", dialingCode: 237 },
  { countryCode: "CN", dialingCode: 86 },
  { countryCode: "CO", dialingCode: 57 },
  { countryCode: "CR", dialingCode: 506 },
  { countryCode: "CU", dialingCode: 53 },
  { countryCode: "CV", dialingCode: 238 },
  { countryCode: "CW", dialingCode: 599 },
  { countryCode: "CX", dialingCode: 61 },
  { countryCode: "CY", dialingCode: 357 },
  { countryCode: "CZ", dialingCode: 420 },
  { countryCode: "DE", dialingCode: 49 },
  { countryCode: "DJ", dialingCode: 253 },
  { countryCode: "DK", dialingCode: 45 },
  { countryCode: "DM", dialingCode: 1767 },
  { countryCode: "DO", dialingCode: 1809 },
  { countryCode: "DZ", dialingCode: 213 },
  { countryCode: "EC", dialingCode: 593 },
  { countryCode: "EE", dialingCode: 372 },
  { countryCode: "EG", dialingCode: 20 },
  { countryCode: "EH", dialingCode: 212 },
  { countryCode: "ER", dialingCode: 291 },
  { countryCode: "ES", dialingCode: 34 },
  { countryCode: "ET", dialingCode: 251 },
  { countryCode: "FI", dialingCode: 358 },
  { countryCode: "FJ", dialingCode: 679 },
  { countryCode: "FK", dialingCode: 500 },
  { countryCode: "FM", dialingCode: 691 },
  { countryCode: "FO", dialingCode: 298 },
  { countryCode: "FR", dialingCode: 33 },
  { countryCode: "GA", dialingCode: 241 },
  { countryCode: "GB", dialingCode: 44 },
  { countryCode: "GD", dialingCode: 1473 },
  { countryCode: "GE", dialingCode: 995 },
  { countryCode: "GF", dialingCode: 594 },
  { countryCode: "GG", dialingCode: 44 },
  { countryCode: "GH", dialingCode: 233 },
  { countryCode: "GI", dialingCode: 350 },
  { countryCode: "GL", dialingCode: 299 },
  { countryCode: "GM", dialingCode: 220 },
  { countryCode: "GN", dialingCode: 224 },
  { countryCode: "GP", dialingCode: 590 },
  { countryCode: "GQ", dialingCode: 240 },
  { countryCode: "GR", dialingCode: 30 },
  { countryCode: "GT", dialingCode: 502 },
  { countryCode: "GU", dialingCode: 1671 },
  { countryCode: "GW", dialingCode: 245 },
  { countryCode: "GY", dialingCode: 592 },
  { countryCode: "HK", dialingCode: 852 },
  { countryCode: "HN", dialingCode: 504 },
  { countryCode: "HR", dialingCode: 385 },
  { countryCode: "HT", dialingCode: 509 },
  { countryCode: "HU", dialingCode: 36 },
  { countryCode: "ID", dialingCode: 62 },
  { countryCode: "IE", dialingCode: 353 },
  { countryCode: "IL", dialingCode: 972 },
  { countryCode: "IM", dialingCode: 44 },
  { countryCode: "IN", dialingCode: 91 },
  { countryCode: "IO", dialingCode: 246 },
  { countryCode: "IQ", dialingCode: 964 },
  { countryCode: "IR", dialingCode: 98 },
  { countryCode: "IS", dialingCode: 354 },
  { countryCode: "IT", dialingCode: 39 },
  { countryCode: "JE", dialingCode: 44 },
  { countryCode: "JM", dialingCode: 1876 },
  { countryCode: "JO", dialingCode: 962 },
  { countryCode: "JP", dialingCode: 81 },
  { countryCode: "KE", dialingCode: 254 },
  { countryCode: "KG", dialingCode: 996 },
  { countryCode: "KH", dialingCode: 855 },
  { countryCode: "KI", dialingCode: 686 },
  { countryCode: "KM", dialingCode: 269 },
  { countryCode: "KN", dialingCode: 1869 },
  { countryCode: "KP", dialingCode: 850 },
  { countryCode: "KR", dialingCode: 82 },
  { countryCode: "KW", dialingCode: 965 },
  { countryCode: "KY", dialingCode: 1345 },
  { countryCode: "KZ", dialingCode: 7 },
  { countryCode: "LA", dialingCode: 856 },
  { countryCode: "LB", dialingCode: 961 },
  { countryCode: "LC", dialingCode: 1758 },
  { countryCode: "LI", dialingCode: 423 },
  { countryCode: "LK", dialingCode: 94 },
  { countryCode: "LR", dialingCode: 231 },
  { countryCode: "LS", dialingCode: 266 },
  { countryCode: "LT", dialingCode: 370 },
  { countryCode: "LU", dialingCode: 352 },
  { countryCode: "LV", dialingCode: 371 },
  { countryCode: "LY", dialingCode: 218 },
  { countryCode: "MA", dialingCode: 212 },
  { countryCode: "MC", dialingCode: 377 },
  { countryCode: "MD", dialingCode: 373 },
  { countryCode: "ME", dialingCode: 382 },
  { countryCode: "MF", dialingCode: 590 },
  { countryCode: "MG", dialingCode: 261 },
  { countryCode: "MH", dialingCode: 692 },
  { countryCode: "MK", dialingCode: 389 },
  { countryCode: "ML", dialingCode: 223 },
  { countryCode: "MM", dialingCode: 95 },
  { countryCode: "MN", dialingCode: 976 },
  { countryCode: "MO", dialingCode: 853 },
  { countryCode: "MP", dialingCode: 1670 },
  { countryCode: "MQ", dialingCode: 596 },
  { countryCode: "MR", dialingCode: 222 },
  { countryCode: "MS", dialingCode: 1664 },
  { countryCode: "MT", dialingCode: 356 },
  { countryCode: "MU", dialingCode: 230 },
  { countryCode: "MV", dialingCode: 960 },
  { countryCode: "MW", dialingCode: 265 },
  { countryCode: "MX", dialingCode: 52 },
  { countryCode: "MY", dialingCode: 60 },
  { countryCode: "MZ", dialingCode: 258 },
  { countryCode: "NA", dialingCode: 264 },
  { countryCode: "NC", dialingCode: 687 },
  { countryCode: "NE", dialingCode: 227 },
  { countryCode: "NF", dialingCode: 672 },
  { countryCode: "NG", dialingCode: 234 },
  { countryCode: "NI", dialingCode: 505 },
  { countryCode: "NL", dialingCode: 31 },
  { countryCode: "NO", dialingCode: 47 },
  { countryCode: "NP", dialingCode: 977 },
  { countryCode: "NR", dialingCode: 674 },
  { countryCode: "NU", dialingCode: 683 },
  { countryCode: "NZ", dialingCode: 64 },
  { countryCode: "OM", dialingCode: 968 },
  { countryCode: "PA", dialingCode: 507 },
  { countryCode: "PE", dialingCode: 51 },
  { countryCode: "PF", dialingCode: 689 },
  { countryCode: "PG", dialingCode: 675 },
  { countryCode: "PH", dialingCode: 63 },
  { countryCode: "PK", dialingCode: 92 },
  { countryCode: "PL", dialingCode: 48 },
  { countryCode: "PM", dialingCode: 508 },
  { countryCode: "PR", dialingCode: 1787 },
  { countryCode: "PS", dialingCode: 970 },
  { countryCode: "PT", dialingCode: 351 },
  { countryCode: "PW", dialingCode: 680 },
  { countryCode: "PY", dialingCode: 595 },
  { countryCode: "QA", dialingCode: 974 },
  { countryCode: "RE", dialingCode: 262 },
  { countryCode: "RO", dialingCode: 40 },
  { countryCode: "RS", dialingCode: 381 },
  { countryCode: "RU", dialingCode: 7 },
  { countryCode: "RW", dialingCode: 250 },
  { countryCode: "SA", dialingCode: 966 },
  { countryCode: "SB", dialingCode: 677 },
  { countryCode: "SC", dialingCode: 248 },
  { countryCode: "SD", dialingCode: 249 },
  { countryCode: "SE", dialingCode: 46 },
  { countryCode: "SG", dialingCode: 65 },
  { countryCode: "SH", dialingCode: 290 },
  { countryCode: "SI", dialingCode: 386 },
  { countryCode: "SJ", dialingCode: 47 },
  { countryCode: "SK", dialingCode: 421 },
  { countryCode: "SL", dialingCode: 232 },
  { countryCode: "SM", dialingCode: 378 },
  { countryCode: "SN", dialingCode: 221 },
  { countryCode: "SO", dialingCode: 252 },
  { countryCode: "SR", dialingCode: 597 },
  { countryCode: "SS", dialingCode: 211 },
  { countryCode: "ST", dialingCode: 239 },
  { countryCode: "SV", dialingCode: 503 },
  { countryCode: "SX", dialingCode: 1721 },
  { countryCode: "SY", dialingCode: 963 },
  { countryCode: "SZ", dialingCode: 268 },
  { countryCode: "TA", dialingCode: 290 },
  { countryCode: "TC", dialingCode: 1649 },
  { countryCode: "TD", dialingCode: 235 },
  { countryCode: "TG", dialingCode: 228 },
  { countryCode: "TH", dialingCode: 66 },
  { countryCode: "TJ", dialingCode: 992 },
  { countryCode: "TK", dialingCode: 690 },
  { countryCode: "TL", dialingCode: 670 },
  { countryCode: "TM", dialingCode: 993 },
  { countryCode: "TN", dialingCode: 216 },
  { countryCode: "TO", dialingCode: 676 },
  { countryCode: "TR", dialingCode: 90 },
  { countryCode: "TT", dialingCode: 1868 },
  { countryCode: "TV", dialingCode: 688 },
  { countryCode: "TW", dialingCode: 886 },
  { countryCode: "TZ", dialingCode: 255 },
  { countryCode: "UA", dialingCode: 380 },
  { countryCode: "UG", dialingCode: 256 },
  { countryCode: "US", dialingCode: 1 },
  { countryCode: "UY", dialingCode: 598 },
  { countryCode: "UZ", dialingCode: 998 },
  { countryCode: "VA", dialingCode: 379 },
  { countryCode: "VC", dialingCode: 1784 },
  { countryCode: "VE", dialingCode: 58 },
  { countryCode: "VG", dialingCode: 1284 },
  { countryCode: "VI", dialingCode: 1340 },
  { countryCode: "VN", dialingCode: 84 },
  { countryCode: "VU", dialingCode: 678 },
  { countryCode: "WF", dialingCode: 681 },
  { countryCode: "WS", dialingCode: 685 },
  { countryCode: "XK", dialingCode: 383 },
  { countryCode: "YE", dialingCode: 967 },
  { countryCode: "YT", dialingCode: 262 },
  { countryCode: "ZA", dialingCode: 27 },
  { countryCode: "ZM", dialingCode: 260 },
  { countryCode: "ZW", dialingCode: 263 },
];
